#include "main.h"

//AUTONOMOUS PID TUNING CONSTANTS
////ROTATIONAL CONSTANTS
const double ROTATIONAL_MINIMUM_DERIVATIVE = 0.1;
const int ROTATIONAL_ERROR_EXIT = 10;
const int ROTATIONAL_DERIVATIVE_EXIT = 20;
////TRANSLATION CONSTANTS
const double TRANSLATIONAL_MINIMUM_DERIVATIVE = 0.1;
const int TRANSLATIONAL_DERIVATIVE_EXIT = 5;
//PRECISION CONSTANTS
const int ANALOG_DEAD_ZONE = 20;
const int ROTATION_PRECISION = 1;
const int TRANSLATION_PRECISION = 5;

//DURATION CONSTANTS
//https://www.vexforum.com/t/v5-distance-sensor-technical-details/88482/8
//DISTANCE SENSOR FREQUENCY IS ~30 HZ: jpearman
const int WHILE_LOOP_DELAY_DURATION = 10;
const int DISTANCE_SENSOR_DELAY = 40;

//MOTOR CONSTANTS
const int MAX_VOLTAGE = 127;

